version: '3.7'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: seq_test
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  seq_web:
    image: web_sequelize
    depends_on:
      - db
    build: .
    environment:
      NODE_ENV: production
      DB_HOST: db
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    links:
      - db
volumes:
  data: