version: '3.7'

services:
  db:
    image: mongo:latest
    ports:
      - 5432:5432
    volumes:
      - data:/data/db
  web_seqelize:
    image: web_sequelize
    depends_on:
      - db
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - db
volumes:
  data: